### ISSUE TITLE
Doesn't open modrinth:// links

### ISSUE THREAD

**Issue by kyrosene** [flathub/com.modrinth.ModrinthApp#19]
Modrinth.com has a new menu that appears when you download a mod, which lets you open the Modrinth app. This Flatpak doesn't support opening modrinth:// links yet.

Clicking the button in both Firefox and GNOME Web don't do anything, and GNOME Settings says the Modrinth app doesn't have any link associations, like Discord for example:
![image](https://github.com/user-attachments/assets/db6def6a-f7c3-4fb0-918c-4aafaaf9036e)

**Comment by getchoo** [comment]
Pretty sure this was introduced in 0.8.3 or 0.8.4, so it'll be fixed once we update in https://github.com/flathub/com.modrinth.ModrinthApp/pull/20

**Comment by getchoo** [comment]
This should be fixed with the latest release. Please reopen if not
