### ISSUE TITLE
Error prevents usage upon invocation, after prolonged update.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [flathub/com.modrinth.ModrinthApp#30]
#### **Errata**

As https://github.com/modrinth/code/issues/2515#issuecomment-2417858791 states, when I perform:

```sh
flatpak -vvv install 'https://dl.flathub.org/repo/appstream/com.modrinth.ModrinthApp.flatpakref' && \
flatpak -vvv update  'app/com.modrinth.ModrinthApp/x86_64/stable' --commit=ec083848d78b8259bbae1ef8c1dfebe1fdbd7ad188922f224e2e3b2b6dcdd1fd && \
flatpak -vvv run     'app/com.modrinth.ModrinthApp/x86_64/stable'
```

1. ...the AppImage takes an unusually significant amount of time to attempt to update:

   > ![image](https://github.com/user-attachments/assets/10c91ab5-77e1-41c3-ac5c-66256934aec7)

1. ...then displays an error:

   > ![image](https://github.com/user-attachments/assets/51128e28-41f2-4351-93b4-b1407577dcd4)

#### **Environment**

1.	```sh
	kinfo
	```

1.	> ```YAML
	>       Operating System: Fedora Linux 40
	>     KDE Plasma Version: 6.2.1
	> KDE Frameworks Version: 6.7.0
	>             Qt Version: 6.7.2
	>         Kernel Version: 6.11.3-200.fc40.x86_64 (64-bit)
	>      Graphics Platform: Wayland
	>             Processors: 12 × AMD Ryzen 5 7600X 6-Core Processor
	>                 Memory: 30.5 GiB of RAM
	>     Graphics Processor: AMD Radeon RX 5700
	> ```

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/com.modrinth.ModrinthApp/issues/30#issue-2593074753

Considering that Modrinth has not had any https://github.com/modrinth/code/releases since https://github.com/modrinth/code/releases/tag/v0.7.1, I presume that https://github.com/modrinth/code/releases/tag/v0.8.9 counts as a release published by CI to the client? If so, the Modrinth application's self-updater may be attempting to download that, and failing to do so. Generally, it's a bad idea to have a self-updater in an application installed via a package manager.

**Comment by mirai-toto** [comment]
A friend I introduced to Linux had the same issue on Fedora KDE

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/com.modrinth.ModrinthApp/issues/30#issuecomment-2422648868

@mirai-toto, that's my OS too. I should have initially added environment information. Thanks for reminding me - I'll do so now.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub/com.modrinth.ModrinthApp/issues/30#issue-2593074753

Remediated <= the undermentioned version:

```bash
#!/usr/bin/env -S bash
flatpak install 'https://dl.flathub.org/repo/appstream/com.modrinth.ModrinthApp.flatpakref' --system && \
flatpak update 'app/com.modrinth.ModrinthApp/x86_64/stable' --commit=12863f64fd16c6b0e40bdec4d213243c26cf283c16316364b699161620fddb25
```
